# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/i2cdevlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/i2cdevlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/i2cdevlib/CMakeFiles /home/pi/i2cdevlib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/i2cdevlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Communicator.o: Communicator.cpp.o

.PHONY : Communicator.o

# target to build an object file
Communicator.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Communicator.cpp.o
.PHONY : Communicator.cpp.o

Communicator.i: Communicator.cpp.i

.PHONY : Communicator.i

# target to preprocess a source file
Communicator.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Communicator.cpp.i
.PHONY : Communicator.cpp.i

Communicator.s: Communicator.cpp.s

.PHONY : Communicator.s

# target to generate assembly for a file
Communicator.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Communicator.cpp.s
.PHONY : Communicator.cpp.s

RaspberryPi_bcm2835/I2Cdev/I2Cdev.o: RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.o

.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.o

# target to build an object file
RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.o
.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.o

RaspberryPi_bcm2835/I2Cdev/I2Cdev.i: RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.i

.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.i

# target to preprocess a source file
RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.i
.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.i

RaspberryPi_bcm2835/I2Cdev/I2Cdev.s: RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.s

.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.s

# target to generate assembly for a file
RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.s
.PHONY : RaspberryPi_bcm2835/I2Cdev/I2Cdev.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/jsoncpp/dist/jsoncpp.o: src/jsoncpp/dist/jsoncpp.cpp.o

.PHONY : src/jsoncpp/dist/jsoncpp.o

# target to build an object file
src/jsoncpp/dist/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jsoncpp/dist/jsoncpp.cpp.o
.PHONY : src/jsoncpp/dist/jsoncpp.cpp.o

src/jsoncpp/dist/jsoncpp.i: src/jsoncpp/dist/jsoncpp.cpp.i

.PHONY : src/jsoncpp/dist/jsoncpp.i

# target to preprocess a source file
src/jsoncpp/dist/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jsoncpp/dist/jsoncpp.cpp.i
.PHONY : src/jsoncpp/dist/jsoncpp.cpp.i

src/jsoncpp/dist/jsoncpp.s: src/jsoncpp/dist/jsoncpp.cpp.s

.PHONY : src/jsoncpp/dist/jsoncpp.s

# target to generate assembly for a file
src/jsoncpp/dist/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/jsoncpp/dist/jsoncpp.cpp.s
.PHONY : src/jsoncpp/dist/jsoncpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... Communicator.o"
	@echo "... Communicator.i"
	@echo "... Communicator.s"
	@echo "... RaspberryPi_bcm2835/I2Cdev/I2Cdev.o"
	@echo "... RaspberryPi_bcm2835/I2Cdev/I2Cdev.i"
	@echo "... RaspberryPi_bcm2835/I2Cdev/I2Cdev.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/jsoncpp/dist/jsoncpp.o"
	@echo "... src/jsoncpp/dist/jsoncpp.i"
	@echo "... src/jsoncpp/dist/jsoncpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

